extends Node


@onready var dict = {
	ENM.AB_KEY.RESET : PC_Ability.new(ENM.AB_KEY.RESET, "RESET", 0.0, 0.0, 1.0),
		
	ENM.AB_KEY.POLE_SPIN_KICK : PC_Ability.new(ENM.AB_KEY.POLE_SPIN_KICK, "POLE_SPIN_KICK", 2.0, 2.5, 2.0),
	ENM.AB_KEY.POLE_INVERSION_STRIKE : PC_Ability.new(ENM.AB_KEY.POLE_INVERSION_STRIKE, "POLE_INVERSION_STRIKE", 4.0, 7.5, 1.5),
	ENM.AB_KEY.POLE_INVERSION_DIVE : PC_Ability.new(ENM.AB_KEY.POLE_INVERSION_DIVE, "POLE_INVERSION_DIVE", 6.0, 10.0, 1.5),
	ENM.AB_KEY.POLE_PIROUETTE : PC_Ability.new(ENM.AB_KEY.POLE_PIROUETTE, "POLE_PIROUETTE", 8.0, 0.0, 1.0)
}
