extends Node

enum AB_KEY {
	RESET,
	POLE_SPIN_KICK, 
	POLE_INVERSION_STRIKE, 
	POLE_INVERSION_DIVE,
	POLE_PIROUETTE,
	CARD_DRAW_AND_STORE,
	CARD_REVEAL,
	CARD_JACKPOT,
	CARD_CHEAT
}

# Dancer Ability Keys
var AB_DNC_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.POLE_SPIN_KICK,
	AB_KEY.POLE_INVERSION_STRIKE,
	AB_KEY.POLE_INVERSION_DIVE,
	AB_KEY.POLE_PIROUETTE
]

# Astrologian Ability Keys
var AB_AST_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.CARD_DRAW_AND_STORE,
	AB_KEY.CARD_REVEAL,
	AB_KEY.CARD_JACKPOT,
	AB_KEY.CARD_CHEAT
]

var AB_ATK1_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.POLE_SPIN_KICK
]

var AB_ATK2_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.POLE_SPIN_KICK
]

var AB_ATK3_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.POLE_SPIN_KICK
]

var AB_DEF_KEY:Array[AB_KEY] = [
	AB_KEY.RESET,
	AB_KEY.POLE_SPIN_KICK
]

enum PC {
	ANY,
	DANCER,
	ASTROLOGIAN,
	SCIENTIST,
	THIEF
}

enum TARGET_TYPE {
	NONE,
	ENEMY,
	PLAYER,
	PROJECTILE
}
